package com.feringsapp.biliforge.media.danmaku

import java.util.Locale

/**
 * 弹幕 → ASS（含滚动轨道分配，可直接挂载播放）
 */
object AssWriter {

    private const val LANES = 16

    fun render(
        danmakus: List<Danmaku>,
        playResX: Int = 1920,
        playResY: Int = 1080,
        title: String = "BiliForge",
    ): String {
        val sb = StringBuilder(danmakus.size * 80 + 2048)
        sb.append("[Script Info]\n")
        sb.append("; Generated by BiliForge · ").append(title).append('\n')
        sb.append("ScriptType: v4.00+\n")
        sb.append("PlayResX: ").append(playResX).append('\n')
        sb.append("PlayResY: ").append(playResY).append('\n')
        sb.append("WrapStyle: 2\n")
        sb.append("ScaledBorderAndShadow: yes\n\n")
        sb.append("[V4+ Styles]\n")
        sb.append("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
        sb.append("Style: DM,Microsoft YaHei,")
            .append((playResY * 0.052f).toInt())
            .append(",&H00FFFFFF,&H00FFFFFF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,1.2,1.4,7,30,30,30,1\n\n")
        sb.append("[Events]\n")
        sb.append("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

        val laneFree = FloatArray(LANES)
        val total = danmakus.size
        val sorted = danmakus.sortedBy { it.timeMs }

        for (d in sorted) {
            if (d.mode == 7 || d.mode == 8) continue   // 高级/代码弹幕暂不支持
            val text = sanitize(d.text)
            val color = colorTag(d.color)
            when {
                d.isScroll || d.isReverse -> {
                    val dur = scrollDurationMs(d, playResX)
                    val lane = laneFor(laneFree, d.timeMs, dur)
                    val y = laneY(lane, playResY)
                    val w = estimateWidth(text, d.fontSize, playResX)
                    val x1: Int
                    val x2: Int
                    if (d.isReverse) {
                        x1 = -w; x2 = playResX + w
                    } else {
                        x1 = playResX + w; x2 = -w
                    }
                    sb.append("Dialogue: 0,")
                        .append(assTime(d.timeMs)).append(',')
                        .append(assTime(d.timeMs + dur)).append(',')
                        .append("DM,,0,0,0,,{\\move(")
                        .append(x1).append(',').append(y).append(',')
                        .append(x2).append(',').append(y).append(")}")
                        .append(color).append(text).append('\n')
                }
                d.isTop || d.isBottom -> {
                    val y = if (d.isTop) (playResY * 0.09f).toInt() else (playResY * 0.87f).toInt()
                    sb.append("Dialogue: 0,")
                        .append(assTime(d.timeMs)).append(',')
                        .append(assTime(d.timeMs + 4000)).append(',')
                        .append("DM,,0,0,0,,{\\an8\\pos(")
                        .append(playResX / 2).append(',').append(y).append(")}")
                        .append(color).append(text).append('\n')
                }
            }
        }
        return sb.toString()
    }

    private fun laneFor(lanes: FloatArray, startMs: Long, durMs: Long): Int {
        var idx = 0
        for (i in lanes.indices) {
            if (lanes[i] <= startMs) { idx = i; break }
            if (lanes[i] < lanes[idx]) idx = i
        }
        lanes[idx] = (startMs + durMs).toFloat()
        return idx
    }

    private fun laneY(lane: Int, playResY: Int): Int {
        val top = playResY * 0.045f
        val usable = playResY * 0.80f
        return (top + usable / LANES * lane).toInt()
    }

    private fun scrollDurationMs(d: Danmaku, playResX: Int): Long {
        val w = estimateWidth(d.text, d.fontSize, playResX)
        return (4200L + w * 2L).coerceIn(4200L, 14000L)
    }

    private fun estimateWidth(text: String, fontSize: Int, playResX: Int): Int {
        var units = 0f
        for (ch in text) units += if (ch.code > 0x2E80) 1.0f else 0.55f
        return (units * fontSize * 1.30f * (playResX / 1920f)).toInt()
    }

    private fun colorTag(rgb: Int): String {
        if (rgb == 0xFFFFFF) return ""
        val r = (rgb shr 16) and 0xFF
        val g = (rgb shr 8) and 0xFF
        val b = rgb and 0xFF
        return String.format(Locale.US, "{\\c&H%02X%02X%02X&}", b, g, r)
    }

    private fun sanitize(text: String): String =
        text.replace("\\", "＼")
            .replace("{", "｛")
            .replace("}", "｝")
            .replace("\n", " ")

    private fun assTime(ms: Long): String {
        val h = ms / 3_600_000
        val m = ms % 3_600_000 / 60_000
        val s = ms % 60_000 / 1000
        val cs = ms % 1000 / 10
        return String.format(Locale.US, "%d:%02d:%02d.%02d", h, m, s, cs)
    }
}

/** 弹幕 → SRT（通用字幕） */
object SrtWriter {

    fun render(danmakus: List<Danmaku>): String {
        val sb = StringBuilder(danmakus.size * 48)
        var idx = 1
        for (d in danmakus.sortedBy { it.timeMs }) {
            sb.append(idx++).append('\n')
            sb.append(srtTime(d.timeMs)).append(" --> ")
                .append(srtTime(d.timeMs + 4000)).append('\n')
            sb.append(d.text).append("\n\n")
        }
        return sb.toString()
    }

    private fun srtTime(ms: Long): String {
        val h = ms / 3_600_000
        val m = ms % 3_600_000 / 60_000
        val s = ms % 60_000 / 1000
        val mmm = ms % 1000
        return String.format(Locale.US, "%02d:%02d:%02d,%03d", h, m, s, mmm)
    }
}
